# Netlify deployment configuration for frontend

[build]
  base = "frontend/"
  command = "npm run build"
  publish = "build/"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-api.herokuapp.com"
  REACT_APP_WS_URL = "wss://your-backend-api.herokuapp.com/ws"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
