services:
  # Backend API Service
  - type: web
    name: news-intelligence-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
    healthCheckPath: /health
